import Head from "next/head";
import MovieList from "~/components/MovieList";
import Search from "~/components/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>My movie app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Search />
        <MovieList/>
      </main>
    </>
  );
}
